### ISSUE TITLE
Seeing skull instead of videos

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#35] opened 2017-01-07 23:18 UTC
Hi there,

I wanted to re-open #32, because we are seeing it as well. There doesn't seem to be a reproducible pattern, except that the `WistiaMediaStats` object failed to parse (because of missing data), and as a result the video will not play.

I didn't get a chance to dig into the current implementation too much, but it feels like those two should be decoupled if possible.

**Comment by spinosa** [comment] 2017-01-09 17:39
The `ParserError` is badly named; it's a warning and does not cause the playback issues in the case of #32.  You will see it even when video plays fine (but you probably won't look at the logs in those cases :-] ).

That actual playback problem in #32 was most likely caused by the great firewall.  Some of the results pointed to that being the culprit, but I am still waiting on more detailed results to confirm.

Are you seeing other errors or noticing any patterns when a video doesn't play?  Is it a video that plays sometimes, but occasionally errors?

**Comment by mergesort** [comment] 2017-01-10 16:42
For us it's happening on many but not all videos, of people enrolled in video courses.

[Here](http://embed.wistia.com/deliveries/3b102378e614ba16419afc7c7c3d628cf53b472e/REV-L1-Course_Introduction.mp4) is an example of a video that continuously that leads to a white skull when played like so.

```
let wistiaPlayerViewController = WistiaPlayerViewController()
wistiaPlayerViewController.replaceCurrentVideoWithVideo(forHashedID: "3nvjiyswrj")
self.present(wistiaPlayerViewController, animated: true, completion: nil)
wistiaPlayerViewController.play()
```

Any thoughts on what's wrong, or if I'm misusing the API in some way?

**Comment by need2edit** [comment] 2017-01-10 19:49
@mergesort do you have domain restriction enabled on your Wistia Account? I've had mixed results with the skull icon appearing depending on those settings. Food for thought. 

We opted to keep it off for a number of other internal use cases.

**Comment by mergesort** [comment] 2017-01-10 20:13
Just checked, and we do not have domain restrictions turned on in our Wistia account. [This](http://ankurnagpal.wistia.com/) is our main Wistia account, if it's of any help. 

Any other thoughts or info I can provide that would be helpful?

**Comment by spinosa** [comment] 2017-01-11 18:30
@need2edit We made some updates re: domain restrictions a little while ago.  Domain restrictions should now respect the domain you set via `referrer` in WistiaKit.  If you do see issues, please open a ticket and we'll dig in.

@mergesort I will investigate the video you mentioned above and get back to you.  Should be tomorrow / Friday.

**Comment by mergesort** [comment] 2017-01-11 18:43
Thanks a lot, will eagerly sit around twiddling my thumbs. 🙂

**Comment by need2edit** [comment] 2017-01-11 19:23
@spinosa Thanks a lot for the `referrer` info, I'll revisit with team! No issues on our end so far though.

**Comment by spinosa** [comment] 2017-01-13 17:51
@mergesort what is the hashedID for that video?

FYI: I'm looking into some issues (similar to what you reported) when a video is queued for processing, but I don't think that's what you're seeing.  Possibly related.

**Comment by mergesort** [comment] 2017-01-13 18:04
The hashed ID is `3nvjiyswrj`.

I am fairly certain it's not related to queuing, because these videos have been in our system (and hosted by Wistia) for quite some time now, though I suppose it could be related to some alternative processing on your side.

**Comment by spinosa** [comment] 2017-01-13 20:01
thanks @mergesort .  I tried to reproduce errors, but `3nvjiyswrj` plays fine for me every time.

I could only get it to fail when I had no network connection.  Which you may be experiencing; the result is the same skull-n-bones.

I've got a couple things you could try:
1) Break on `_WistiaPlayerViewController.swift:355` (`WistiaPlayerViewController.presentForError()`) and inspect `wPlayer.state` to see what caused the error
and/or
2) Use the edge WistiaKit directly from GitHub; I've added some alerts for common playback errors

**Comment by mergesort** [comment] 2017-01-18 18:20
@spinosa Sorry for the delay.

This is the error that shows.
```
ParserError(message: "The key \'visitors\' was not found.")
```

And `wPlayer.state` is this.

```
videoPlaybackError : "Player Item Failed"
```

That's why my suspicion is that it has to do `WistiaMediaStats`.

**Comment by mergesort** [comment] 2017-01-18 18:34
It looks like that might be a red herring. I changed the WistiaStats constructor to this:

```
init?(from dictionary: [String: Any]?) {
    pageLoads = 0
    visitors = 0
    percentOfVisitorsClickingPlay = 0
    plays = 0
    averagePercentWatched = 0
}
```

And am still getting this error.

```
videoPlaybackError : "Player Item Failed"
```

**Comment by spinosa** [comment] 2017-01-19 02:35
@mergesort  yes, the parsing is a red herring.  Indeed, `WistiaKit` v 0.19 fixes the stats parsing issues you mentioned.

_Player Item Failed_ is an error coming from `AVFoundation`.  The `AVPlayerItem` (https://developer.apple.com/reference/avfoundation/avplayeritem) is failing and hopefully its error will help us diagnose the issue...

At the same breakpoint from above (`WistiaPlayerViewController.presentForError()`), when you get the "Player Item Failed" message, you can see the underlying AVFoundation error by inspecting `wPlayer.currentItem?.error` in the debugger.

Let's take a look at that.

---

Some other things to make sure we're covering our bases:

- Are you requiring HLS on the wistia player?
- Have you seen this issue with and without HLS? If so, any correlation?
- Have you seen this issue on cellular vs wifi?  If so, any correlation?

**Comment by mergesort** [comment] 2017-01-19 15:56
`wPlayer.currentItem?.error` is 
```
Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x608000850dd0 {Error Domain=NSOSStatusErrorDomain Code=-16190 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-16190), NSLocalizedDescription=The operation could not be completed}
```

• We are not currently requiring HLS, just using a constructor of `WistiaPlayerViewController()` which defaults HLS to no.
• I tried turning HLS on, and it still is erroring out.
• There seems to be no correlation between wifi and cellular connection.

**Comment by spinosa** [comment] 2017-01-20 02:43
@mergesort Unfortunately that's one of the less helpful errors.

I've tested that video (hash `3nvjiyswrj`) in the bare WistiaKit example app and still cannot reproduce any errors (it plays fine for me 100% of the time).

At the moment, I'm at a bit of a loss of ideas...  @mrdavidjcole maybe there's something on the delivery side we can look at?  Or have you any other debug ideas?

**Comment by mrdavidjcole** [comment] 2017-01-20 04:13
This is just a hunch, but perhaps re-encoding the video will help. (This particular video was uploaded back in 2014, and doesn't have all the derivatives that we'd encode if it were uploaded today). 

I just did that, so the video has a fresh set encodes now, hot out of the oven. 

Any change, @mergesort?

**Comment by mergesort** [comment] 2017-01-20 15:10
I just tried to load it and it still failed with a skull. The hash now is `9us5vldd85` as opposed to `3nvjiyswrj`, should that have occurred? 

I'm going to try and put together a barebones project and make sure I see the same thing.

**Comment by mrdavidjcole** [comment] 2017-01-20 18:17
Hm, the only video I took any action on is `3nvjiyswrj`, which still exists and now has a fresh set of derivative assets. `9us5vldd85` looks like the same content, but is a separate video in Wistia, and was uploaded back in 2014 as well.

The problem is still happening with `3nvjiyswrj` ?

**Comment by mergesort** [comment] 2017-01-20 19:17
It is still happening. I threw it into an empty project as @spinosa suggested, and it does work. I got it isolated and reproducible in a tiny sample project here.

[WistiaTest.zip](https://github.com/wistia/WistiaKit/files/720286/WistiaTest.zip)

**Comment by mergesort** [comment] 2017-01-25 04:54
@mrdavidjcole @spinosa Any chance y'all could look at the sample project above when you have a chance?

**Comment by spinosa** [comment] 2017-01-25 15:56
@mergesort I haven't forgotten about this, or you :-]

What code, exactly, is instantiating the `WistiaPlayerViewController`?  

I know you said you aren't requiring HLS, but I just noticed some unexpected behavior in WK.  If you don't explicitly use the convenience initializer `WistiaPlayerViewController(referrer:,requireHLS:)` then it will default to `requiredHLS=true` via the designated initializer.  For instance, if you instantiate directly from Storyboard or Xib, the default constructor is used and `requireHLS=true`.

This will causes any video without HLS - like many older videos - to fail.

You can check using the same breakpoint we've been using to debug this error.  When you break, inspect `wPlayer.requireHLS`

**Comment by mergesort** [comment] 2017-01-25 16:18
That is incredibly strange, because the default constructor (which I'm calling in code, not a storyboard) looks like this, explicitly setting `requiresHLS: Bool = false`.

```swift
public convenience init(referrer: String, requireHLS: Bool = false) {
    self.init()
    self.referrer = referrer
    self.requireHLS = requireHLS

    self.modalPresentationStyle = .fullScreen
}```

Despite that, `wPlayer.requireHLS` is indeed set to true at the breakpoint. Any thoughts as to why this would be?

It is working now on this video when setting it directly to false, though I can't confirm on all videos. I would suggest making sure that it is indeed set to false in places, because based on this discussion I'd imagine the Wistia corpus is not all HLS encoded.

**Comment by spinosa** [comment] 2017-01-25 16:39
If you were calling `WistiaPlayerViewController()` that will use the designated initializer, not the convenience constructor you mention.

I am changing the designated initiatialization such that `requireHSL=false`.  That will be in v0.19.1

**Closed by spinosa** 2017-01-25 16:39 UTC

**Comment by mergesort** [comment] 2017-01-25 17:48
Ahh, that makes sense. Alrighty then, well thank you for all the time and energy you put into this @spinosa and @mrdavidjcole, it's highly appreciated!

**Comment by mrdavidjcole** [comment] 2017-01-25 17:52
Thanks @spinosa 🙌
