### ISSUE TITLE
Error trying to play a video

### ISSUE THREAD

**Issue by mergesort** [wistia/WistiaKit#80] opened 2017-12-14 16:41 UTC
Our users are running into the skull and cross bones screen on some videos and we can't figure out why. We're using version 0.30.2 on the `djs/xcode9` branch.

Here is the hashed id for the video in question. 
```
f35n0ngsrl
```

The call-site is pretty simple, just loading the video and playing it.
```swift
let wistiaPlayerViewController = WistiaPlayerViewController(referrer: "", requireHLS: false)
wistiaPlayerViewController.replaceCurrentVideoWithVideo(forHashedID: theVideoIdInQuestion)
self.present(wistiaPlayerViewController, animated: true, completion: nil)
wistiaPlayerViewController.play()
```

The error that comes through in playerItem.error is this.
```
Error Domain=AVFoundationErrorDomain Code=-11800 "Media format - sample description is invalid (e.g. invalid size)" UserInfo={NSUnderlyingError=0x600000845340 {Error Domain=NSOSStatusErrorDomain Code=-12714 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-12714), NSDebugDescription=Media format - sample description is invalid (e.g. invalid size), NSLocalizedDescription=The operation could not be completed}
```

Following the call stack, it goes into these two functions, hitting the error cases in each instance.

`_WistiaPlayer.swift`
```swift
internal func playerItem(_ playerItem:AVPlayerItem, statusWas oldStatus:AVPlayerStatus?, changedTo newStatus:AVPlayerStatus){
    switch newStatus {
    case .failed:
        self.state = .videoPlaybackError(description: "Player Item Failed")
    }
}
```

`_WistiaPlayerViewController.swift`
```swift
internal func presentForError(_ errorState: WistiaPlayer.State) {
    switch errorState {
    case .videoPlaybackError(let desc):
        alertAbout(title: "Video Playback Problem", message: desc)
    }
}
```

Let me know if there's any more information I can provide.

Thanks a lot!

**Comment by mergesort** [comment] 2017-12-14 17:08
Digging into it a bit more, it appears the videos that are being sent down may not be encoded correctly. If you try to open the [media link](https://embed-ssl.wistia.com/deliveries/18da64450e64034c5255a3894bbe93dc291c3591.bin) that is sent down and played, in Safari, it does not seem to work, rendering this screen instead.

![Renders as this instead of playing](https://user-images.githubusercontent.com/716513/34004955-704127b8-e0c7-11e7-994c-2246f3b96a8a.png)

We've tried re-encoding the videos as the Wistia service provides us the option, but are not able to get it to work. Is there anything we can do to ensure the integrity of the videos, as well as surfacing this in the API so the users don't just see a skull and crossbones image without any information?

**Comment by spinosa** [comment] 2017-12-20 21:14
Hi @mergesort ,

I've brought this media to the attention of some other folks who are digging in.  Will keep you posted /cc @jayholman 

As for WistiaKit handling errors; I agree that it should be _much_ better.  I've started work on WistiaKit2 (which is being built to use the still-under-constructions Wistia API v2).  It's designed from the ground up to do a much better job with issues like this.  Would appreciate your feedback at this early stage if you have some spare time to check out the `wk2` branch

**Comment by jayholman** [comment] 2017-12-20 21:29
Hey @mergesort we've been running some tests on that Media and noticed that the HLS derivatives in general seemed to have some trouble that was visible when playing them back normally. After taking a look at the mediainfo for the original file, it looked pretty normal except that it did have a pretty low bitrate (1692 kb/s). We tried running a test boosting the bitrate up in Handbrake to 6000 kb/s and then re-uploading it. That boost seems to solve the problem, here's the m3u8 for that test media: https://fast.wistia.net/embed/medias/f0e9fkpaeg.m3u8

Ideally keeping the bitrate up in our recommended export settings should avoid this sorts of issues in the future (https://wistia.com/doc/export-settings)

**Comment by noahpryor** [comment] 2017-12-21 19:36
Any chance you could expose the bit rate in the api so we could warn customers proactively? We've got 1.5 million videos hosted with you guys, downloading and spot checking each manually isn't super viable for us. (I work with @mergesort )

**Comment by jayholman** [comment] 2017-12-21 20:24
hi @noahpryor I appreciate exposing bitrate via an API would be helpful, and I can pass that along to our PMs. It's not something we can easily add quickly.

For this case it seems like there might be something unique about the media beyond the bit rate so we've been continuing to look further into what specifically went on and caused problems. 1600 is on the lower end of bitrates and seemed (based on the tests) to be the problem, but it's possible it could have been a red herring and that something else running it through handbrake solved the problem. 

For a solution moving forward, we're looking into what might have caused the HLS problems specific to the media and what we can put in place to prevent this sort of problem programmatically in the future. It should be considered essentially a failed encode which can happen in any instance for a variety of reasons that we try to detect programmatically. We will continue working to see if we can adjust to better recognize/handle those through the encoding infrastructure so it wouldn't be necessary for you poll the api for bitrate.

If it's required, approximate average bitrate can be computed based on the API response like this `asset.fileSize / media.duration`.

Since this issue relates to the encoding on this particular media and the issues occurred outside of WistiaKit, we're going to close this issue. If you have continued questions/concerns, we'd be happy to continue working with you through our support inbox (support@wistia.com).

**Closed by jayholman** 2017-12-21 20:24 UTC

**Comment by noahpryor** [comment] 2017-12-21 20:50
But this happens on thousands of our videos, not 'one particular one' we just used that as an example, since flooding your github issue with thousands of video ids seemed not great.

**Comment by jayholman** [comment] 2017-12-21 21:09
Hey @noahpryor, that makes sense. I appreciate you not putting all those IDs here, but it is good to know that it's actually wider spread. Can you email us at support@wistia.com and we'll take things from there? It would be awesome if we can figure out a way to programmatically identify the commonalities amongst the problematic files so that we can deal with them at scale. The support inbox would be a better medium to continue working through this issue though.

**Comment by jayholman** [comment] 2017-12-22 15:31
Hi @noahpryor and @mergesort we wanted to let you know about an update on this issue. We confirmed that the bitrate for that file was a red herring and have determined that the issue was related to the original file's colorspace. It uses the YUV 4:4:4 colorspace which was preventing Safari, iOS, and Firefox playback because it was used on the accompanying derivatives. Handbrake converted the original to YUV 4:2:0 and resolved the issue. Here's a comparison between the colorspaces on the file in question first and a control file below:
Problem:
```
Colorimetry                              : 4:4:4
Color space                              : YUV
Chroma subsampling                       : 4:4:4
```
Control:
```
Colorimetry                              : 4:2:0
Color space                              : YUV
Chroma subsampling                       : 4:2:0
````
We've implemented a fix in our encoding infrastructure that adds logic to convert any files uploaded with the YUV 4:4:4 colorspace when they are uploaded so that they use YUV 4:2:0 instead. This should prevent any issues with future uploads like this one in question.
